### PR TITLE
add security audit review

### PR DESCRIPTION
**Pull request by ronnno**

### CODE REVIEW

**Comment by ronnno** [comment]
@talkol please review the change itself for changes
@itamararjuan CI breaks

**Comment by talkol** [comment]
why didn't you add the third one (Bok)?

**Comment by talkol** [comment]
I would use a different link inside Bok, since what he did is fork the token repo and put his comments inside.. you put the link to the fork. When somebody like an exchange tries to open this to read the review, they don't see anything...

This should be the correct link:

https://github.com/bokkypoobah/OrbsSubscriptionSmartContractAudit/tree/alpha/audit

But please go over this yourself in detail

**Comment by ronnno** [comment]
@talkol in the page I used there is a reference to the page you specify. Since you say there is no additional or interesting information in [this](https://github.com/bokkypoobah/OrbsTokenSmartContractAudit) repo I am removing this link and keeping only the link you specify.

**Pull request merged**
